CREATE SCHEMA dbo;

CREATE TABLE dbo.Geral_Paciente (
  CodPaciente int NOT NULL,
  Nome varchar (100) NOT NULL,
  Sexo char (1) NOT NULL,
  DataNascimento varchar (50) NULL,
  Familia varchar (50) NULL,
  MicroArea varchar (50) NULL,
  Equipe varchar (50) NULL,
  Telefone varchar (30) NULL,
  Celular varchar (30) NULL,
  EstadoCivil varchar (50) NULL,
  Logradouro varchar (150) NULL,
  Numero int NULL,
  Bairro varchar (100) NULL,
  CodMunicipio int NULL,
  Complemento varchar (100) NULL,
  Referencia varchar (200) NULL,
  Profissao varchar (100) NULL,
  CartaoSUS varchar (15) NULL,
  NumeroProntuario varchar (15) NULL,
  TipoDocumento int NULL,
  NumeroDocumento varchar (50) NULL,
  OrgaoEmissor varchar (50) NULL,
  EstadoOrgaoEmissor varchar (15) NULL,
  Observacoes varchar  NULL,
  DataCriacao VARCHAR(30),  -- datetime NOT NULL,
  DataAlteracao VARCHAR(30), -- datetime NULL,
  CodPessoa bigint NULL,
  CodBairro int NULL,
  CNESOrigem varchar (20) NULL,
  PacienteOcasional  varchar (5),-- false ou true bit NOT NULL,
  Falecido  varchar (5),-- false ou truebit NOT NULL,
  DataPrevistaParto VARCHAR(30),  -- datetime NULL,
  CodEstado int NULL,
  NomePai varchar (100) NULL,
  NomeMae varchar (100) NULL,
  CodRacaCor int,  -- NOT NULL CONSTRAINT DF__Geral_pac__CodRa__52AE4273 DEFAULT (99),
  Cep varchar (9) NULL,
  CodUsuarioCadSUS varchar (60) NULL,
  Email varchar (100) NULL,
  ReceberNotificacao  varchar (5),-- false ou true bit NOT NULL CONSTRAINT DF__Geral_Pac__Receb__5F691F13 DEFAULT (0),
  CodPaisOrigem varchar (3) NULL,
  CodTipoLogradouro varchar (3) NULL,
  CodEscolaridade varchar (3) NULL,
  CodEstadoCivil varchar (2) NULL,
  NomeContato varchar (100) NULL,
  NomeResponsavelLegal varchar (100) NULL,
  CodEstadoOrigem int NULL,
  CodMunicipioOrigem int NULL,
  FrequentaInstituicaoEnsino varchar (5),--bit NOT NULL CONSTRAINT DF__Geral_Pac__Frequ__605D434C DEFAULT (0),
  CodTipoVinculoProfissional int, -- tinyint NULL,
  RegistroFuncional varchar (10) NULL,
  HorarioTrabalho varchar (16) NULL,
  NumeroContaBancaria varchar (10) NULL,
  AgenciaBancaria varchar (5) NULL,
  CodTipoContaBancaria   int, -- tinyint NULL,
  Banco varchar (50) NULL,
  LoginResponsavel varchar (25) NULL,
  RGNumero varchar (20) NULL,
  RGUF varchar (2) NULL,
  CPF varchar (11) NULL,
  NomeNormalizado varchar (100) NULL,
  EntregouComprovanteResidencia varchar (5),-- bit NULL,
  Gemeo  varchar (5),--bit NULL,
  NomeSocial varchar (100) NULL,
  NomeInstituicao varchar (250) NULL,
  PacienteSituacaoRua varchar (5),--bit NOT NULL,
  NIS varchar (11) NULL,
  CodTipoOcorrencia int, -- NULL CONSTRAINT DF__Geral_Pac__CodTi__12149A71 DEFAULT (26),
  GrauParentescoContato varchar (50) NULL,
  IdadeAproximada varchar (5) --bit NOT NULL CONSTRAINT DF__Geral_Pac__Idade__13FCE2E3 DEFAULT (0),
 );
  
 COPY dbo.geral_paciente FROM   'C:/tmp/csv/pacientes.csv' HEADER CSV;
